import { NextResponse } from 'next/server';
import { createClient } from '@supabase/supabase-js';
import { requireAdmin } from '../../../../lib/admin-auth';

const getSupabase = () => {
  const url = process.env.NEXT_PUBLIC_SUPABASE_URL;
  const key = process.env.SUPABASE_SERVICE_ROLE_KEY || process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;
  if (!url || !key) return null;
  return createClient(url, key);
};

const VALID_STATUSES = ['Draft', 'Sent', 'Partial', 'Paid'];

// GET: List invoices with patient info
export async function GET(request: Request) {
  const { error: authError } = await requireAdmin();
  if (authError) return authError;

  const supabase = getSupabase();
  if (!supabase) return NextResponse.json({ error: 'Server configuration error' }, { status: 500 });

  const { searchParams } = new URL(request.url);
  const patientId = searchParams.get('patient_id');
  const consultationId = searchParams.get('consultation_id');
  const status = searchParams.get('status') || '';
  const search = searchParams.get('search') || '';
  const limit = Math.min(Number(searchParams.get('limit') || '50'), 200);

  try {
    let query = supabase
      .from('invoices')
      .select(`
        *,
        patients:patient_id (id, name, phone, email),
        invoice_items (id, description, amount, patient_treatment_id),
        payments (id, amount, method, date, transaction_id, notes)
      `)
      .order('created_at', { ascending: false })
      .limit(limit);

    if (patientId) query = query.eq('patient_id', patientId);
    if (consultationId) query = query.eq('consultation_id', consultationId);
    if (status) query = query.eq('status', status);

    if (search) {
      // Search by invoice number or patient name
      const { data: matchingPatients } = await supabase
        .from('patients')
        .select('id')
        .or(`name.ilike.%${search}%,phone.ilike.%${search}%`);

      if (matchingPatients && matchingPatients.length > 0) {
        const patientIds = matchingPatients.map(p => p.id);
        query = query.or(`invoice_number.ilike.%${search}%,patient_id.in.(${patientIds.join(',')})`);
      } else {
        query = query.ilike('invoice_number', `%${search}%`);
      }
    }

    const { data, error } = await query;
    if (error) {
      if (error.code === 'PGRST205' || error.code === '42P01') {
        return NextResponse.json({ data: [] });
      }
      throw error;
    }
    return NextResponse.json({ data });
  } catch {
    return NextResponse.json({ error: 'Failed to fetch invoices' }, { status: 500 });
  }
}

// POST: Create an invoice (optionally from a consultation's treatments)
export async function POST(request: Request) {
  const { error: authError } = await requireAdmin();
  if (authError) return authError;

  const supabase = getSupabase();
  if (!supabase) return NextResponse.json({ error: 'Server configuration error' }, { status: 500 });

  try {
    const body = await request.json();
    const { patient_id, consultation_id, items, discount, notes } = body;

    if (!patient_id || typeof patient_id !== 'string') {
      return NextResponse.json({ error: 'Patient is required' }, { status: 400 });
    }

    // Calculate totals
    const lineItems = Array.isArray(items) ? items : [];
    const subtotal = lineItems.reduce((sum: number, item: { amount?: number }) => sum + (Number(item.amount) || 0), 0);
    const discountAmount = Math.max(0, Math.min(Number(discount) || 0, subtotal));
    const total = subtotal - discountAmount;

    // Create invoice (invoice_number auto-generated by trigger)
    const invoiceRecord: Record<string, unknown> = {
      invoice_number: '', // trigger will set this
      patient_id,
      subtotal,
      discount: discountAmount,
      total,
      paid_amount: 0,
      status: 'Draft',
    };
    if (consultation_id) invoiceRecord.consultation_id = consultation_id;
    if (notes) invoiceRecord.notes = notes;

    const { data: invoice, error: invoiceError } = await supabase
      .from('invoices')
      .insert([invoiceRecord])
      .select()
      .single();

    if (invoiceError) throw invoiceError;

    // Insert line items
    if (lineItems.length > 0) {
      const itemRecords = lineItems.map((item: { description?: string; amount?: number; patient_treatment_id?: string }) => ({
        invoice_id: invoice.id,
        description: item.description || 'Treatment',
        amount: Number(item.amount) || 0,
        patient_treatment_id: item.patient_treatment_id || null,
      }));

      const { error: itemsError } = await supabase.from('invoice_items').insert(itemRecords);
      if (itemsError) throw itemsError;
    }

    // Fetch complete invoice with items
    const { data: fullInvoice, error: fetchError } = await supabase
      .from('invoices')
      .select(`
        *,
        patients:patient_id (id, name, phone, email),
        invoice_items (id, description, amount, patient_treatment_id),
        payments (id, amount, method, date, transaction_id, notes)
      `)
      .eq('id', invoice.id)
      .single();

    if (fetchError) throw fetchError;
    return NextResponse.json({ success: true, data: fullInvoice });
  } catch {
    return NextResponse.json({ error: 'Failed to create invoice' }, { status: 500 });
  }
}

// PATCH: Update an invoice
export async function PATCH(request: Request) {
  const { error: authError } = await requireAdmin();
  if (authError) return authError;

  const supabase = getSupabase();
  if (!supabase) return NextResponse.json({ error: 'Server configuration error' }, { status: 500 });

  try {
    const body = await request.json();
    const { id, ...updates } = body;
    if (!id) return NextResponse.json({ error: 'Missing ID' }, { status: 400 });

    const sanitized: Record<string, unknown> = { updated_at: new Date().toISOString() };
    if (updates.discount !== undefined) sanitized.discount = Number(updates.discount) || 0;
    if (updates.notes !== undefined) sanitized.notes = updates.notes;
    if (updates.status && VALID_STATUSES.includes(updates.status)) {
      sanitized.status = updates.status;
    }

    // Recalculate total if discount changed
    if (updates.discount !== undefined) {
      const { data: currentInvoice } = await supabase
        .from('invoices')
        .select('subtotal')
        .eq('id', id)
        .single();

      if (currentInvoice) {
        const newDiscount = Math.max(0, Math.min(Number(updates.discount), Number(currentInvoice.subtotal)));
        sanitized.discount = newDiscount;
        sanitized.total = Number(currentInvoice.subtotal) - newDiscount;
      }
    }

    const { data, error } = await supabase.from('invoices').update(sanitized).eq('id', id).select(`
      *,
      patients:patient_id (id, name, phone, email),
      invoice_items (id, description, amount, patient_treatment_id),
      payments (id, amount, method, date, transaction_id, notes)
    `);
    if (error) throw error;
    return NextResponse.json({ success: true, data });
  } catch {
    return NextResponse.json({ error: 'Failed to update invoice' }, { status: 500 });
  }
}

// DELETE: Remove an invoice
export async function DELETE(request: Request) {
  const { error: authError } = await requireAdmin();
  if (authError) return authError;

  const supabase = getSupabase();
  if (!supabase) return NextResponse.json({ error: 'Server configuration error' }, { status: 500 });

  const { searchParams } = new URL(request.url);
  const id = searchParams.get('id');
  if (!id) return NextResponse.json({ error: 'Missing ID' }, { status: 400 });

  try {
    // Check if there are payments
    const { data: payments } = await supabase.from('payments').select('id').eq('invoice_id', id).limit(1);
    if (payments && payments.length > 0) {
      return NextResponse.json({ error: 'Cannot delete invoice with existing payments' }, { status: 400 });
    }

    const { error } = await supabase.from('invoices').delete().eq('id', id);
    if (error) throw error;
    return NextResponse.json({ success: true });
  } catch {
    return NextResponse.json({ error: 'Failed to delete invoice' }, { status: 500 });
  }
}
